### ISSUE TITLE
Failing tests (possibly) due to missing lib

### ISSUE THREAD

**Issue by linssen** [cameronprattedwards/ko-genius#1]
Looks like the lib [`../genius-base-spec.js`](https://github.com/cameronprattedwards/ko-genius/blob/master/karma.conf.js#L18) is not included in the project, which is probably causing three failing tests:

```
Resource flags should be ko.observables FAILED
        TypeError: undefined is not a function
            at null.<anonymous> (/path/to/ko-genius/ko-genius-spec.js:32:17)
Collections should be observable arrays FAILED
        TypeError: undefined is not a function
            at null.<anonymous> (/path/to/ko-genius/ko-genius-spec.js:84:17)
Resource requests should parse queries into resources FAILED
        TypeError: undefined is not a function
            at null.<anonymous> (/path/to/ko-genius/ko-genius-spec.js:182:17)
Executed 10 of 10 (3 FAILED) (0.052 secs / 0.046 secs)
```

I wonder if you'd consider adding a `package.json` and any instructions for running the tests / contributing to the project?

**Comment by cameronprattedwards** [comment]
@linssen Thanks for creating an issue! I fixed the tests, updated the README, and added both NPM and Bower packages. 

If you don't mind my asking, how did you find this project?

**Comment by linssen** [comment]
It's still missing the `devDepenencies` which I'd suggest are probably `karma`, `karma-chrome-launcher`, and `karma-jasmine`. After that the tests pass for me. I'm not sure of the bower deps, though?

Found you through https://github.com/knockout/knockout/wiki/Plugins whilst looking for a nicer way to map from JSON.

**Comment by cameronprattedwards** [comment]
@linssen Thanks. Added those dependencies. Let me know if you need anything else.

**Comment by linssen** [comment]
All good, cheers!
